version: "3"

services:
  grpc-server:
    build: ./server
    volumes:
      - ./server:/home/grpc-test/server
#    image: grpc-server
    ports:
      - 9000:9000
    container_name: "grpc-server"
  grpc-client:
    build: ./client
    volumes:
      - ./client:/home/grpc-test/client
#    image: grpc-client
    restart: always
    depends_on:
      - grpc-server
