version: "3"

services:
  grpc-server:
    build: ./server
#    image: grpc-server
    ports:
      - 9000:9000
    container_name: "grpc-server"
  grpc-client:
    build: ./client
#    image: grpc-client
#    restart: always
    depends_on:
      - grpc-server
